### ISSUE TITLE
Test of API 

### ISSUE THREAD

**Issue by GabrielFrancellinMoretti** [tavicu/test-samsung-api#1]
Hello, i'am trying to put this integration with samsung smart tv 2016+ but the communication by websocket doesnt work.
I'am even try to capture the protocol between some others integrations with wireshark but is all TLS communication.
I test your API and have this following log:

---------------------

getInfo - start
getInfo - response {
  device: {
    FrameTVSupport: 'false',
    GamePadSupport: 'true',
    ImeSyncedSupport: 'true',
    Language: 'pt_BR',
    OS: 'Tizen',
    PowerState: 'on',
    TokenAuthSupport: 'true',
    VoiceSupport: 'true',
    WallScreenRatio: '0',
    WallService: 'false',
    countryCode: 'BR',
    description: 'Samsung DTV RCR',
    developerIP: '0.0.0.0',
    developerMode: '0',
    duid: 'uuid:5f9c2750-7421-4ba4-90a6-9b2acc06acc1',
    firmwareVersion: 'Unknown',
    id: 'uuid:5f9c2750-7421-4ba4-90a6-9b2acc06acc1',
    ip: '10.0.0.162',
    model: '20_NIKEL_UHD',
    modelName: 'QN50Q60TAGXZD',
    name: '[TV] TV Sala Reunião',
    networkType: 'wireless',
    resolution: '3840x2160',
    smartHubAgreement: 'true',
    ssid: 'fc:ec:da:35:2a:62',
    type: 'Samsung SmartTV',
    udn: 'uuid:5f9c2750-7421-4ba4-90a6-9b2acc06acc1',
    wifiMac: 'D0:D0:03:F1:38:EA'
  },
  id: 'uuid:5f9c2750-7421-4ba4-90a6-9b2acc06acc1',
  isSupport: {
    DMP_DRM_PLAYREADY: 'false',
    DMP_DRM_WIDEVINE: 'false',
    DMP_available: 'true',
    EDEN_available: 'true',
    FrameTVSupport: 'false',
    ImeSyncedSupport: 'true',
    TokenAuthSupport: 'true',
    remote_available: 'true',
    remote_fourDirections: 'true',
    remote_touchPad: 'true',
    remote_voiceControl: 'true'
  },
  name: '[TV] TV Sala Reunião',
  remote: '1.0',
  type: 'Samsung SmartTV',
  uri: 'http://10.0.0.162:8001/api/v2/',
  version: '2.0.25'
}

---------------------

testBaseWs - start
testBaseWs - message {
  data: {
    clients: [ [Object] ],
    id: 'e344b5c5-d45-4d9f-8ea9-c112a284e476',
    token: '93727575'
  },
  event: 'ms.channel.connect'
}

testBaseWs - send command
testBaseWs - send command - error undefined
testBaseWs - terminate

---------------------

testArtWs - start
testArtWs - message {
  data: { clients: [ [Object] ], id: '8a1e662f-4c16-4bf4-94a-60e7d130d495' },
  event: 'ms.channel.connect'
}

testArtWs - send getStatus
testArtWs - send getStatus - error undefined
testArtWs - terminate

---------------------

If you have some information about what iam doing wrong or something we can help each other.  Thanks

**Comment by tavicu** [comment]
Hi.

Looks like the script is connecting to the websocket with success and the plugin uses the same exact code as the script.
Are you sure you get the IP right in config file?

You could start the homebridge in debug mode (`homebridge -D`) and then we will be able to see what the plugin returns when you send a command or if we get an error.

Also, when you run this script, at `testBaseWs - send command` step it sends a Volume Up command, does the TV get the command? Does the volume go up?

**Comment by GabrielFrancellinMoretti** [comment]
Hi, 
Thanks I got it here. 
My device was in the deny list.
